export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SEND_CONFIRMATION_EMAIL = 'SEND_CONFIRMATION_EMAIL';
export const RESEND_CONFIRMATION_EMAIL = 'RESEND_CONFIRMATION_EMAIL';
export const SEND_PASSWORD_RESET_LINK = 'SEND_PASSWORD_RESET_LINK';
export const VERIFY_USER = 'VERIFY_USER';
